apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: anumate-audit
  labels:
    app: audit-service
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
        version: v1.0.0
    spec:
      containers:
      - name: audit-service
        image: anumate/audit-service:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8007
          name: http
        envFrom:
        - configMapRef:
            name: audit-service-config
        - secretRef:
            name: audit-service-secrets
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8007
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - name: audit-exports
          mountPath: /app/exports
        - name: audit-logs
          mountPath: /app/logs
      volumes:
      - name: audit-exports
        persistentVolumeClaim:
          claimName: audit-exports-pvc
      - name: audit-logs
        emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
