apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: anumate-audit
  labels:
    app: audit-service
spec:
  selector:
    app: audit-service
  ports:
  - port: 80
    targetPort: 8007
    protocol: TCP
    name: http
  type: ClusterIP
