global:
  evaluation_interval: 15s
  scrape_interval: 15s
scrape_configs:
- job_name: audit-service
  metrics_path: /metrics
  scrape_interval: 10s
  static_configs:
  - targets:
    - audit-service:8007
