version: '3.8'
services:
  audit-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8007:8007
    environment:
    - DATABASE_URL=postgresql+asyncpg://audit:audit_pass@audit-db:5432/audit_db
    - REDIS_URL=redis://audit-redis:6379/0
    - LOG_LEVEL=INFO
    - ENVIRONMENT=production
    - EXPORT_DIRECTORY=/app/exports
    - RETENTION_CHECK_INTERVAL=3600
    volumes:
    - audit_exports:/app/exports
    - audit_logs:/app/logs
    depends_on:
    - audit-db
    - audit-redis
    networks:
    - audit-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
  audit-db:
    image: postgres:15
    environment:
    - POSTGRES_DB=audit_db
    - POSTGRES_USER=audit
    - POSTGRES_PASSWORD=audit_pass
    volumes:
    - audit_db_data:/var/lib/postgresql/data
    - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - 5432:5432
    networks:
    - audit-network
    restart: unless-stopped
    command:
    - postgres
    - -c
    - max_connections=200
    - -c
    - shared_buffers=256MB
    - -c
    - effective_cache_size=1GB
    - -c
    - work_mem=4MB
    - -c
    - maintenance_work_mem=64MB
  audit-redis:
    image: redis:7-alpine
    ports:
    - 6379:6379
    volumes:
    - audit_redis_data:/data
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
    - audit-network
    restart: unless-stopped
    command:
    - redis-server
    - /usr/local/etc/redis/redis.conf
  audit-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - DATABASE_URL=postgresql+asyncpg://audit:audit_pass@audit-db:5432/audit_db
    - REDIS_URL=redis://audit-redis:6379/0
    - LOG_LEVEL=INFO
    - ENVIRONMENT=production
    - EXPORT_DIRECTORY=/app/exports
    volumes:
    - audit_exports:/app/exports
    - audit_logs:/app/logs
    depends_on:
    - audit-db
    - audit-redis
    networks:
    - audit-network
    restart: unless-stopped
    command:
    - python
    - -m
    - src.anumate_audit_service.worker
volumes:
  audit_db_data: {}
  audit_redis_data: {}
  audit_exports: {}
  audit_logs: {}
networks:
  audit-network:
    driver: bridge
