[tool.poetry]
name = "anumate-events"
version = "0.1.0"
description = "CloudEvents models and event bus interfaces for the Anumate platform."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
cloudevents = "^1.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
