[tool.poetry]
name = "anumate-http"
version = "0.1.0"
description = "Resilient HTTP client for the Anumate platform."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.23.0"
anumate-tracing = {path = "../anumate-tracing", develop = true}
anumate-tenancy = {path = "../anumate-tenancy", develop = true}

[tool.poetry.dev-dependencies]
pytest = "^7.0"
respx = "^0.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
