[tool.poetry]
name = "anumate-planhash"
version = "0.1.0"
description = "Deterministic plan hash generation for the Anumate platform."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
anumate-crypto = {path = "../anumate-crypto", develop = true}

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
